### ISSUE TITLE
The "release" job should only run at release time

### ISSUE THREAD

**Issue by szepeviktor** [villfa/test-phar-gpg#10]
... so when the current commit is tagged with a certain version.

In GHA language:

```yaml
on:
  push:
    tags:
      - "v*"
```
